name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Notify server
      uses: joelwmale/webhook-action@2.1.0
      with:
        url: "${{ secrets.deployment_api_url }}"
        headers: '{"X-API-KEY": "${{ secrets.deployment_api_key }}"}'
        body: '{"event": "deployment", "repository": "felpsey/felpsey.com"}'
