name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Deploy
      uses: joelwmale/webhook-action@2.1.0
      with:
        url: ${{ secrets.deployment_api_url }}
        headers: '{"repository": "felpsey/felpsey.com"}'
        body: '{"event": "deployment", "repository": "felpsey/felpsey.com", "key": ${{ secrets.deployment_api_key }}}'
